# Generated by Django 6.1.1 on 2026-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listener",
            name="money",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
