# Generated by Django 6.1.1 on 2026-10-04 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_listener_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listener",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
