# Generated by Django 6.1.1 on 2026-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_alter_listener_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="full_duration",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="song",
            name="duration",
            field=models.DurationField(),
        ),
    ]
