# Generated by Django 6.1.1 on 2026-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_alter_album_full_duration_alter_song_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="songs",
            field=models.ManyToManyField(
                blank=True, related_name="moods", to="music.song"
            ),
        ),
    ]
